### ISSUE TITLE
Mob kill doesnt update 

### ISSUE THREAD

**Issue by Daenarys** [sniffingpickles/RareAnnouncer#1]
Whenever the mobs gets killed, the tracker doesnt register that its killed and stays on "Alive"

**Comment by Daenarys** [comment]
It also doesn't announce in General chat that the mob has been killed. 
Probably cuz it doesn't recognize the mob has been killed ;)

**Comment by sniffingpickles** [comment]
I'll try and find the issue for that; 

Do you have LUA errors turned on?

**Comment by Daenarys** [comment]
I do have LUA errors turned on. 
Don't get any errors though!
Probably some function that was changed by Blizzard in patches after MoP

**Comment by sniffingpickles** [comment]
Yup, I have to rebuild the function for when a unit dies; no problem.  easy fix. 

I actually got the take-over rights to the project on curseforge,  I'll push an updated version after this weekend

**Comment by Daenarys** [comment]
Cool, thanks for your work so far! :)
